// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SabaBot.Database;

#nullable disable

namespace SabaBot.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0-preview.6.24327.4");

            modelBuilder.Entity("SabaBot.Database.GuildSettings", b =>
                {
                    b.Property<ulong>("GuildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.HasKey("GuildId");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("SabaBot.Database.GuildSettings", b =>
                {
                    b.OwnsOne("SabaBot.Database.ReactionChampSettings", "ReactionChampSettings", b1 =>
                        {
                            b1.Property<ulong>("GuildSettingsGuildId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("EmoteId")
                                .HasColumnType("TEXT");

                            b1.Property<bool>("Enabled")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("ReactionThreshold")
                                .HasColumnType("INTEGER");

                            b1.HasKey("GuildSettingsGuildId");

                            b1.ToTable("Guilds");

                            b1.WithOwner()
                                .HasForeignKey("GuildSettingsGuildId");

                            b1.OwnsMany("SabaBot.Database.RewindMessage", "DeletedMessages", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("INTEGER");

                                    b2.Property<ulong>("AuthorId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<ulong>("ReactionChampSettingsGuildSettingsGuildId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Text")
                                        .IsRequired()
                                        .HasMaxLength(1000)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("Id");

                                    b2.HasIndex("ReactionChampSettingsGuildSettingsGuildId");

                                    b2.ToTable("Guilds_DeletedMessages");

                                    b2.WithOwner()
                                        .HasForeignKey("ReactionChampSettingsGuildSettingsGuildId");
                                });

                            b1.Navigation("DeletedMessages");
                        });

                    b.OwnsOne("SabaBot.Database.RewardSettings", "RewardSettings", b1 =>
                        {
                            b1.Property<ulong>("GuildSettingsGuildId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("ClanTag")
                                .HasMaxLength(5)
                                .HasColumnType("TEXT");

                            b1.Property<string>("FilePaths")
                                .HasColumnType("TEXT");

                            b1.Property<string>("MessageText")
                                .HasColumnType("TEXT");

                            b1.HasKey("GuildSettingsGuildId");

                            b1.ToTable("Guilds");

                            b1.WithOwner()
                                .HasForeignKey("GuildSettingsGuildId");
                        });

                    b.OwnsOne("SabaBot.Database.RewindSettings", "RewindSettings", b1 =>
                        {
                            b1.Property<ulong>("GuildSettingsGuildId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("AutomaticRepliesCooldown")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("CooldownCounter")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("EnableAutomaticReplies")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("EnablePingReplies")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("MessagesThreshold")
                                .HasColumnType("INTEGER");

                            b1.HasKey("GuildSettingsGuildId");

                            b1.ToTable("Guilds");

                            b1.WithOwner()
                                .HasForeignKey("GuildSettingsGuildId");

                            b1.OwnsMany("SabaBot.Database.RewindMessage", "Messages", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("INTEGER");

                                    b2.Property<ulong>("AuthorId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<ulong>("RewindSettingsGuildSettingsGuildId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Text")
                                        .IsRequired()
                                        .HasMaxLength(1000)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("Id");

                                    b2.HasIndex("RewindSettingsGuildSettingsGuildId");

                                    b2.ToTable("Guilds_Messages");

                                    b2.WithOwner()
                                        .HasForeignKey("RewindSettingsGuildSettingsGuildId");
                                });

                            b1.Navigation("Messages");
                        });

                    b.Navigation("ReactionChampSettings")
                        .IsRequired();

                    b.Navigation("RewardSettings")
                        .IsRequired();

                    b.Navigation("RewindSettings")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
