name: Deploy to Production
run-name: Deploy 

on:
  push:
    branches:
      - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    env: 
      NAME: saba-bot
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t ${{ env.NAME }}:latest .

      - name: Save Docker image
        run: docker save ${{ env.NAME }}:latest -o ${{ env.NAME }}.tar

      - name: Copy to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "${{ env.NAME }}.tar"
          target: "/home/${{ secrets.VPS_USER }}/"

      - name: Deploy on VPS
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            docker load -i /home/${{ secrets.VPS_USER }}/${{ env.NAME }}.tar
            docker stop ${{ env.NAME }} || true
            docker rm ${{ env.NAME }} || true
            docker run -d \
              -v /home/${{ secrets.VPS_USER }}/data:/data \
              --name ${{ env.NAME }} \
              ${{ env.NAME }}:latest \
              /data/saba-bot/config.json
            rm /home/${{ secrets.VPS_USER }}/${{ env.NAME }}.tar
